# Generated by Django 6.1.1 on 2026-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_service',
            fields=[
                ('Car_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField()),
                ('Car_Model', models.CharField()),
                ('Phone_No', models.IntegerField()),
                ('Address', models.TextField()),
                ('Problem', models.CharField()),
                ('Brand', models.CharField()),
            ],
        ),
    ]
